// #include <stdio.h>
// #include <string.h>
// #include <stdbool.h>

// #include "app.h"
// #include "socket.h"
// #include "arpa/inet.h"
// #include "sl_assert.h"
// #include "sl_cmsis_os2_common.h"
// #include "sl_iostream.h"

// /*
//  * Generated by the ESP32 IO Stream instance.
//  */
// extern sl_iostream_instance_info_t sl_iostream_instance_esp32_info;

// #define UDP_DESTINATION_PORT 5000

// /* ------------------------------------------------------------------------- */
// /* Global variables                                                          */
// /* ------------------------------------------------------------------------- */

// static int udp_socket_id = -1;
// static sockaddr_in6_t udp_destination;

// /* ------------------------------------------------------------------------- */
// /* UDP initialization                                                        */
// /* ------------------------------------------------------------------------- */

// static void udp_init(void)
// {
//   int result;

//   /*
//    * Create an IPv6 UDP socket.
//    */
//   udp_socket_id = socket(AF_INET6, SOCK_DGRAM, IPPROTO_UDP);

//   if (udp_socket_id < 0) {
//     printf("ERROR: UDP socket() failed\r\n");
//     return;
//   }

//   printf("UDP socket created: %d\r\n", udp_socket_id);

//   /*
//    * Clear destination structure.
//    */
//   memset(&udp_destination, 0, sizeof(udp_destination));

//   /*
//    * IPv6 address family.
//    */
//   udp_destination.sin6_family = AF_INET6;

//   /*
//    * Destination UDP port.
//    */
//   udp_destination.sin6_port = htons(UDP_DESTINATION_PORT);

//   /*
//    * Raspberry Pi Border Router IPv6 address.
//    */
//   result = inet_pton(
//       AF_INET6,
//       "fd12:3456::92fd:9fff:feee:9d54",
//       &udp_destination.sin6_addr);

//   if (result != 1) {
//     printf("ERROR: inet_pton() failed\r\n");

//     close(udp_socket_id);
//     udp_socket_id = -1;

//     return;
//   }

//   printf("UDP destination configured\r\n");
// }

// /* ------------------------------------------------------------------------- */
// /* UART receive task                                                         */
// /* ------------------------------------------------------------------------- */

// static void esp32_uart_task(void *args)
// {
//   (void)args;

//   char c;
//   char rx_line[128];
//   size_t rx_length = 0;

//   printf("ESP32 UART task started\r\n");

//   while (1) {

//     /*
//      * Wait for one character from the ESP32 UART.
//      *
//      * This may block while no character is available.
//      * That is OK because this is a dedicated UART task.
//      */
//     if (sl_iostream_getchar(
//           sl_iostream_instance_esp32_info.handle,
//           &c) == SL_STATUS_OK) {

//       /*
//        * Ignore carriage return.
//        */
//       if (c == '\r') {
//         continue;
//       }

//       /*
//        * Newline means the complete message has arrived.
//        */
//       if (c == '\n') {

//         rx_line[rx_length] = '\0';

//         printf("ESP32 RX: %s\r\n", rx_line);

//         rx_length = 0;
//       }

//       /*
//        * Store normal characters.
//        */
//       else if (rx_length < (sizeof(rx_line) - 1)) {

//         rx_line[rx_length++] = c;
//       }

//       /*
//        * Prevent buffer overflow.
//        */
//       else {

//         printf("ESP32 UART buffer overflow\r\n");

//         rx_length = 0;
//       }
//     }
//   }
// }

// /* ------------------------------------------------------------------------- */
// /* UART task attributes                                                      */
// /* ------------------------------------------------------------------------- */

// static const osThreadAttr_t esp32_uart_task_attr = {
//   .name = "ESP32UART",
//   .attr_bits = osThreadDetached,
//   .cb_mem = NULL,
//   .cb_size = 0,
//   .stack_mem = NULL,
//   .stack_size = 1024,
//   .priority = osPriorityNormal,
//   .tz_module = 0
// };

// /* ------------------------------------------------------------------------- */
// /* Main application task                                                     */
// /* ------------------------------------------------------------------------- */

// void app_task(void *args)
// {
//   (void)args;

//   /*
//    * Join the Wi-SUN network and wait until connected.
//    */
//   sl_wisun_app_core_util_connect_and_wait();

//   printf("Wi-SUN connected\r\n");

//   /*
//    * Initialize UDP socket.
//    */
//   udp_init();

//   /*
//    * Make sure the ESP32 IO Stream exists.
//    */
//   if (sl_iostream_instance_esp32_info.handle == NULL) {

//     printf("ERROR: ESP32 IO Stream handle is NULL\r\n");

//     return;
//   }

//   printf("ESP32 IO Stream ready\r\n");

//   /*
//    * Create a dedicated UART receive task.
//    */
//   osThreadId_t uart_task_id = osThreadNew(
//       esp32_uart_task,
//       NULL,
//       &esp32_uart_task_attr);

//   if (uart_task_id == NULL) {

//     printf("ERROR: Failed to create ESP32 UART task\r\n");

//     return;
//   }

//   printf("ESP32 UART task created\r\n");

//   /*
//    * Main Wi-SUN application loop.
//    */
//   while (1) {

//     sl_wisun_app_core_util_dispatch_thread();

//     osDelay(10);
//   }
// }

#include <stdio.h>

#include "app.h"
#include "em_gpio.h"
#include "sl_cmsis_os2_common.h"

void app_task(void *args)
{
  (void)args;

  /* Configure PA6 as push-pull output, initially LOW */
  GPIO_PinModeSet(gpioPortA, 6, gpioModePushPull, 0);

  /* Configure PA7 as push-pull output, keep LOW */
  GPIO_PinModeSet(gpioPortA, 7, gpioModePushPull, 0);

  /* PA6 = LOW, PA7 = HIGH */
  GPIO_PinOutClear(gpioPortA, 6);
  GPIO_PinOutSet(gpioPortA, 7);

  printf("TEST B: PA6=LOW, PA7=HIGH\r\n");

  while (1) {
    osDelay(1000);
  }
}